[package]
name = "ft_lex_lib"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
insta = { version = "1.42.2", features = ["yaml"] }
serde = { version = "1.0.219", features = ["derive"] }
rstest = "0.25.0"